import type { Product } from "@/types/catalog";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    sku: "RICE-BAS-PRM-50KG",
    name: "Shudh Premium 1121 Basmati Rice",
    description:
      "Export quality aged 1121 Basmati rice with extra long grain elongation (8.35mm average grain length). Cultivated in the fertile foothills of Punjab & Haryana. Specially aged for 24 months to ensure non-sticky cooking, pearly white luster, and rich sweet aroma.",
    category_id: "cat-1",
    category_name: "Rice & Grains",
    brand: "Shudh Brand",
    hsn_code: "10063020",
    uom: "BAG",
    weight_grams: 50000,
    mrp: 4500,
    status: "active",
    created_at: "2026-01-10T10:00:00Z",
    updated_at: "2026-01-10T10:00:00Z",
  },
  {
    id: "prod-2",
    sku: "RICE-KLM-CLS-25KG",
    name: "Shudh Kolam Rice Classic",
    description:
      "Daily table rice with soft texture, mild natural aroma, and high swelling index. Popular in western and southern India. Sourced from Wada and Raigad paddy fields.",
    category_id: "cat-1",
    category_name: "Rice & Grains",
    brand: "Shudh Brand",
    hsn_code: "10063010",
    uom: "BAG",
    weight_grams: 25000,
    mrp: 1850,
    status: "active",
    created_at: "2026-01-12T11:30:00Z",
    updated_at: "2026-01-12T11:30:00Z",
  },
  {
    id: "prod-3",
    sku: "OIL-SNF-TIN-15L",
    name: "Shudh Refined Sunflower Oil 15L Tin",
    description:
      "Triple-refined cooking oil enriched with Vitamins A & D. Low absorption formula with high smoke point (232°C), ideal for deep frying and commercial food processing.",
    category_id: "cat-2",
    category_name: "Edible Oils",
    brand: "Shudh Gold",
    hsn_code: "15121910",
    uom: "TIN",
    weight_grams: 15000,
    mrp: 2150,
    status: "active",
    created_at: "2026-01-15T09:00:00Z",
    updated_at: "2026-01-15T09:00:00Z",
  },
  {
    id: "prod-4",
    sku: "DAL-TOR-UNP-30KG",
    name: "Shudh Unpolished Toor Dal",
    description:
      "Natural protein-rich farm-fresh Toor Dal, unpolished without water, oil or marble powder polishing. Sourced directly from Latur and Gulbarga farmer producer groups.",
    category_id: "cat-3",
    category_name: "Pulses & Dals",
    brand: "Shudh Brand",
    hsn_code: "07136000",
    uom: "BAG",
    weight_grams: 30000,
    mrp: 3600,
    status: "active",
    created_at: "2026-02-01T14:15:00Z",
    updated_at: "2026-02-01T14:15:00Z",
  },
  {
    id: "prod-5",
    sku: "AGR-NPK-BAG-50KG",
    name: "Kisan Shakti NPK 19:19:19 Water Soluble",
    description:
      "100% water-soluble balanced NPK fertilizer for fertigation and foliar application. Promotes root elongation, vigorous vegetative growth, and flower retention.",
    category_id: "cat-5",
    category_name: "Fertilizers & Agri Inputs",
    brand: "Kisan Shakti",
    hsn_code: "31052000",
    uom: "BAG",
    weight_grams: 50000,
    mrp: 1250,
    status: "active",
    created_at: "2026-02-15T16:00:00Z",
    updated_at: "2026-02-15T16:00:00Z",
  },
  {
    id: "prod-6",
    sku: "OIL-MST-BOT-1L",
    name: "Heritage Kachi Ghani Mustard Oil 1L",
    description:
      "Traditional cold-pressed pungent mustard oil retaining natural antioxidants, omega-3 fatty acids, and authentic mustard aroma.",
    category_id: "cat-2",
    category_name: "Edible Oils",
    brand: "Heritage",
    hsn_code: "15149110",
    uom: "PACK",
    weight_grams: 1000,
    mrp: 165,
    status: "inactive",
    created_at: "2026-03-01T10:00:00Z",
    updated_at: "2026-03-01T10:00:00Z",
  },
];

